site_name: Spigot Sounds
site_description: 'A collection of all known Spigot Sound names, ranging from 1.8 up to 1.17'
site_author: 'Andre_601'

#
# This section uses normal HTML, so normal HTML tags and specific text like &copy; are supported
copyright: |
  &copy; <a href="https://github.com/Andre601" target="_blank" rel="nofollow">Andre601</a>

docs_dir: docs/

#
# These three options are optional.
repo_name: Andre601/Spigot-Sounds
repo_url: https://github.com/Andre601/Spigot-Sounds
#edit_uri: tree/master/docs # If you want the Edit option/URL to be different.

theme:
  name: 'material'
  #
  # Uncomment the below option to use the "theme extension" option
  # to customize certain aspects of the Material Theme.
  #
  #custom_dir: 'theme'
  #
  # https://squidfunk.github.io/mkdocs-material/getting-started/#favicon
  favicon: 'assets/img/logo.jpg'
  #
  # https://squidfunk.github.io/mkdocs-material/getting-started/#color-palette
  palette:
    # Uncomment this option, if you want to use the dark theme of MkDocs-Material.
    scheme: 'slate'
    primary: 'amber'
    accent: 'yellow'
  #
  # https://squidfunk.github.io/mkdocs-material/getting-started/#feature-flags
  features:
    #- instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
  #
  # https://squidfunk.github.io/mkdocs-material/getting-started/#icons
  icon:
    logo: 'octicons/unmute-24'
    repo: 'octicons/mark-github-16'

#
# You can uncomment this line together with the line below to have additional CSS settings.
#extra_css:
#  - 'assets/css/extensions/tabbed.css' # Uncomment this line if you only want the CSS for tabbed

extra:
  #
  # https://squidfunk.github.io/mkdocs-material/getting-started/#adding-social-links
  social:
    - icon: 'octicons/mark-github-16'
      link: 'https://github.com/Andre601/Spigot-Sounds'
  #
  # https://squidfunk.github.io/mkdocs-material/getting-started/#adding-a-web-app-manifest
  #manifest: manifest.webmanifest

plugins:
- search
- awesome-pages
- pagenav-generator

markdown_extensions:
  - markdown.extensions.admonition:
  - markdown.extensions.toc:
      permalink: true
  - markdown.extensions.meta:
  #
  # Uncomment the PyMdown extension you want to use.
  # Note that some might need additional settings to be added.
  #
  # Refer to the official documentation for more info:
  # - https://facelessuser.github.io/pymdown-extensions/
  #
  #- pymdownx.arithmex:
  #- pymdownx.b64:
  #- pymdownx.betterem:
  #- pymdownx.caret:
  #- pymdownx.critic:
  #- pymdownx.details:
  #- pymdownx.emoji:
  #- pymdownx.escapeall:
  #- pymdownx.extra:
  #- pymdownx.extrarawhtml:
  - pymdownx.highlight:
  #- pymdownx.inlinehilite:
  #- pymdownx.keys:
  - pymdownx.magiclink:
  #- pymdownx.mark:
  #- pymdownx.pathconverter:
  #- pymdownx.progressbar:
  #- pymdownx.smartsymbols:
  #- pymdownx.snippets:
  #- pymdownx.striphtml:
  #- pymdownx.superfences:
  #- pymdownx.tabbed: # This extension requires the 'tabbed.css' to be used.
  #- pymdownx.tasklist:
  #- pymdownx.tilde:
