site_name: Spigot Sounds
site_description: 'A collection of all known Spigot Sound names, ranging from 1.8 up to 1.19'
site_author: 'Andre_601'

copyright: |
  &copy; <a href="https://github.com/Andre601" target="_blank" rel="nofollow">Andre601</a>

docs_dir: docs/

repo_name: Andre601/Spigot-Sounds
repo_url: https://github.com/Andre601/Spigot-Sounds

theme:
  name: 'material'
  favicon: 'assets/img/logo.jpg'
  palette:
    scheme: 'slate'
    primary: 'custom'
    accent: 'yellow'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
  icon:
    logo: 'simple/spigotmc'
    repo: 'octicons/mark-github-16'
    admonition:
      note: octicons/pencil-24
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

extra_css:
  - 'assets/css/theme.css'

extra:
  social:
    - icon: 'octicons/mark-github-16'
      link: 'https://github.com/Andre601/Spigot-Sounds'

plugins:
  - search
  - redirects:
      redirect_maps:
        'sounds/index.md': 'sounds/1.21.x/index.md'
        'sounds/mc-1.8.md': 'index.md'
        'sounds/mc-1.9.md': 'sounds/1.9.x/index.md'
        'sounds/mc-1.10.md': 'sounds/1.10.x/index.md'
        'sounds/mc-1.11.md': 'sounds/1.11.x/index.md'
        'sounds/mc-1.12.md': 'sounds/1.12.x/index.md'
        'sounds/mc-1.13.md': 'sounds/1.13.x/index.md'
        'sounds/mc-1.14.md': 'sounds/1.14.x/index.md'
        'sounds/mc-1.15.md': 'sounds/1.15.x/index.md'
        'sounds/mc-1.16.md': 'sounds/1.16.x/index.md'
        'sounds/mc-1.17.md': 'sounds/1.17.x/index.md'
        'sounds/mc-1.18.md': 'sounds/1.18.x/index.md'
        'sounds/mc-1.19.md': 'sounds/1.19.x/index.md'
        'sounds/mc-1.20.md': 'sounds/1.20.x/index.md'
        'sounds/mc-1.20.5.md': 'sounds/1.20.x/index.md'

markdown_extensions:
  - markdown.extensions.md_in_html:
  - markdown.extensions.toc:
      permalink: true
  - markdown.extensions.meta:
  - markdown.extensions.attr_list:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
  - pymdownx.magiclink:
  - pymdownx.blocks.admonition:
      types:
        - note
        - abstract
        - info
        - tip
        - success
        - question
        - warning
        - failure
        - danger
        - bug
        - example
        - quote
        - experimental

nav:
  - index.md
  - Sounds:
    - 1.21.x:
      - sounds/1.21.x/index.md
      - sounds/1.21.x/1.21.4.md
      - sounds/1.21.x/1.21.2.md
      - sounds/1.21.x/1.21.md
    - 1.20.x:
      - sounds/1.20.x/index.md
      - sounds/1.20.x/1.20.5.md
      - sounds/1.20.x/1.20.3.md
      - sounds/1.20.x/1.20.2.md
      - sounds/1.20.x/1.20.md
    - 1.19.x:
      - sounds/1.19.x/index.md
      - sounds/1.19.x/1.19.4.md
      - sounds/1.19.x/1.19.3.md
      - sounds/1.19.x/1.19.md
    - 1.18.x:
      - sounds/1.18.x/index.md
      - sounds/1.18.x/1.18.md
    - 1.17.x:
      - sounds/1.17.x/index.md
      - sounds/1.17.x/1.17.md
    - 1.16.x:
      - sounds/1.16.x/index.md
      - sounds/1.16.x/1.16.2.md
      - sounds/1.16.x/1.16.1.md
    - 1.15.x:
      - sounds/1.15.x/index.md
      - sounds/1.15.x/1.15.md
    - 1.14.x:
      - sounds/1.14.x/index.md
      - sounds/1.14.x/1.14.md
    - 1.13.x:
      - sounds/1.13.x/index.md
      - sounds/1.13.x/1.13.md
    - 1.12.x:
      - sounds/1.12.x/index.md
      - sounds/1.12.x/1.12.md
    - 1.11.x:
      - sounds/1.11.x/index.md
      - sounds/1.11.x/1.11.md
    - 1.10.x:
      - sounds/1.10.x/index.md
      - sounds/1.10.x/1.10.md
    - 1.9.x:
      - sounds/1.9.x/index.md
      - sounds/1.9.x/1.9.2.md