name: Deploy Site

on:
  push:
    paths:
      - '.github/workflows/deploy.yml'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Setup Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools
          python -m pip install -r requirements.txt
      - name: Build Site
        run: mkdocs build
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: site/
      - name: Deploy Site
        id: deploy
        uses: actions/deploy-pages@v4
